/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as GamesRouteImport } from './routes/games'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as RadionetoRouteImport } from './routes/radioneto'
import { Route as Hub2dConceptualRouteImport } from './routes/hub.2d-conceptual'
import { Route as Hub2dCreaturesRouteImport } from './routes/hub.2d-creatures'
import { Route as Hub3dMeshRouteImport } from './routes/hub.3d-mesh'
import { Route as HubComicsRouteImport } from './routes/hub.comics'
import { Route as HubMinitoiresRouteImport } from './routes/hub.minitoires'
import { Route as HubRiggingRouteImport } from './routes/hub.rigging'
import { Route as HubScriptableRouteImport } from './routes/hub.scriptable'
import { Route as HubToolboxRouteImport } from './routes/hub.toolbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const RadionetoRoute = RadionetoRouteImport.update({
  id: '/radioneto',
  path: '/radioneto',
  getParentRoute: () => rootRouteImport,
} as any)
const Hub2dConceptualRoute = Hub2dConceptualRouteImport.update({
  id: '/hub/2d-conceptual',
  path: '/hub/2d-conceptual',
  getParentRoute: () => rootRouteImport,
} as any)
const Hub2dCreaturesRoute = Hub2dCreaturesRouteImport.update({
  id: '/hub/2d-creatures',
  path: '/hub/2d-creatures',
  getParentRoute: () => rootRouteImport,
} as any)
const Hub3dMeshRoute = Hub3dMeshRouteImport.update({
  id: '/hub/3d-mesh',
  path: '/hub/3d-mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const HubComicsRoute = HubComicsRouteImport.update({
  id: '/hub/comics',
  path: '/hub/comics',
  getParentRoute: () => rootRouteImport,
} as any)
const HubMinitoiresRoute = HubMinitoiresRouteImport.update({
  id: '/hub/minitoires',
  path: '/hub/minitoires',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRiggingRoute = HubRiggingRouteImport.update({
  id: '/hub/rigging',
  path: '/hub/rigging',
  getParentRoute: () => rootRouteImport,
} as any)
const HubScriptableRoute = HubScriptableRouteImport.update({
  id: '/hub/scriptable',
  path: '/hub/scriptable',
  getParentRoute: () => rootRouteImport,
} as any)
const HubToolboxRoute = HubToolboxRouteImport.update({
  id: '/hub/toolbox',
  path: '/hub/toolbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/games': typeof GamesRoute
  '/marketplace': typeof MarketplaceRoute
  '/radioneto': typeof RadionetoRoute
  '/hub/2d-conceptual': typeof Hub2dConceptualRoute
  '/hub/2d-creatures': typeof Hub2dCreaturesRoute
  '/hub/3d-mesh': typeof Hub3dMeshRoute
  '/hub/comics': typeof HubComicsRoute
  '/hub/minitoires': typeof HubMinitoiresRoute
  '/hub/rigging': typeof HubRiggingRoute
  '/hub/scriptable': typeof HubScriptableRoute
  '/hub/toolbox': typeof HubToolboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/games': typeof GamesRoute
  '/marketplace': typeof MarketplaceRoute
  '/radioneto': typeof RadionetoRoute
  '/hub/2d-conceptual': typeof Hub2dConceptualRoute
  '/hub/2d-creatures': typeof Hub2dCreaturesRoute
  '/hub/3d-mesh': typeof Hub3dMeshRoute
  '/hub/comics': typeof HubComicsRoute
  '/hub/minitoires': typeof HubMinitoiresRoute
  '/hub/rigging': typeof HubRiggingRoute
  '/hub/scriptable': typeof HubScriptableRoute
  '/hub/toolbox': typeof HubToolboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/games': typeof GamesRoute
  '/marketplace': typeof MarketplaceRoute
  '/radioneto': typeof RadionetoRoute
  '/hub/2d-conceptual': typeof Hub2dConceptualRoute
  '/hub/2d-creatures': typeof Hub2dCreaturesRoute
  '/hub/3d-mesh': typeof Hub3dMeshRoute
  '/hub/comics': typeof HubComicsRoute
  '/hub/minitoires': typeof HubMinitoiresRoute
  '/hub/rigging': typeof HubRiggingRoute
  '/hub/scriptable': typeof HubScriptableRoute
  '/hub/toolbox': typeof HubToolboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/community'
    | '/games'
    | '/marketplace'
    | '/radioneto'
    | '/hub/2d-conceptual'
    | '/hub/2d-creatures'
    | '/hub/3d-mesh'
    | '/hub/comics'
    | '/hub/minitoires'
    | '/hub/rigging'
    | '/hub/scriptable'
    | '/hub/toolbox'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/community'
    | '/games'
    | '/marketplace'
    | '/radioneto'
    | '/hub/2d-conceptual'
    | '/hub/2d-creatures'
    | '/hub/3d-mesh'
    | '/hub/comics'
    | '/hub/minitoires'
    | '/hub/rigging'
    | '/hub/scriptable'
    | '/hub/toolbox'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/community'
    | '/games'
    | '/marketplace'
    | '/radioneto'
    | '/hub/2d-conceptual'
    | '/hub/2d-creatures'
    | '/hub/3d-mesh'
    | '/hub/comics'
    | '/hub/minitoires'
    | '/hub/rigging'
    | '/hub/scriptable'
    | '/hub/toolbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  GamesRoute: typeof GamesRoute
  MarketplaceRoute: typeof MarketplaceRoute
  RadionetoRoute: typeof RadionetoRoute
  Hub2dConceptualRoute: typeof Hub2dConceptualRoute
  Hub2dCreaturesRoute: typeof Hub2dCreaturesRoute
  Hub3dMeshRoute: typeof Hub3dMeshRoute
  HubComicsRoute: typeof HubComicsRoute
  HubMinitoiresRoute: typeof HubMinitoiresRoute
  HubRiggingRoute: typeof HubRiggingRoute
  HubScriptableRoute: typeof HubScriptableRoute
  HubToolboxRoute: typeof HubToolboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radioneto': {
      id: '/radioneto'
      path: '/radioneto'
      fullPath: '/radioneto'
      preLoaderRoute: typeof RadionetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/2d-conceptual': {
      id: '/hub/2d-conceptual'
      path: '/hub/2d-conceptual'
      fullPath: '/hub/2d-conceptual'
      preLoaderRoute: typeof Hub2dConceptualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/2d-creatures': {
      id: '/hub/2d-creatures'
      path: '/hub/2d-creatures'
      fullPath: '/hub/2d-creatures'
      preLoaderRoute: typeof Hub2dCreaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/3d-mesh': {
      id: '/hub/3d-mesh'
      path: '/hub/3d-mesh'
      fullPath: '/hub/3d-mesh'
      preLoaderRoute: typeof Hub3dMeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/comics': {
      id: '/hub/comics'
      path: '/hub/comics'
      fullPath: '/hub/comics'
      preLoaderRoute: typeof HubComicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/minitoires': {
      id: '/hub/minitoires'
      path: '/hub/minitoires'
      fullPath: '/hub/minitoires'
      preLoaderRoute: typeof HubMinitoiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/rigging': {
      id: '/hub/rigging'
      path: '/hub/rigging'
      fullPath: '/hub/rigging'
      preLoaderRoute: typeof HubRiggingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/scriptable': {
      id: '/hub/scriptable'
      path: '/hub/scriptable'
      fullPath: '/hub/scriptable'
      preLoaderRoute: typeof HubScriptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/toolbox': {
      id: '/hub/toolbox'
      path: '/hub/toolbox'
      fullPath: '/hub/toolbox'
      preLoaderRoute: typeof HubToolboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  GamesRoute: GamesRoute,
  MarketplaceRoute: MarketplaceRoute,
  RadionetoRoute: RadionetoRoute,
  Hub2dConceptualRoute: Hub2dConceptualRoute,
  Hub2dCreaturesRoute: Hub2dCreaturesRoute,
  Hub3dMeshRoute: Hub3dMeshRoute,
  HubComicsRoute: HubComicsRoute,
  HubMinitoiresRoute: HubMinitoiresRoute,
  HubRiggingRoute: HubRiggingRoute,
  HubScriptableRoute: HubScriptableRoute,
  HubToolboxRoute: HubToolboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
