// @ts-nocheck
// Additional Japanese verbs from the user-provided list (alphabetical).
// Each tuple: [romaji, japaneseRaw, englishMeaning, group]
//   group: 'i' = ichidan, 'g' = godan
// japaneseRaw may be "hiragana+kanji" (e.g. "あびる浴びる"), kanji-only, or "" (use romaji).
import { romaji2kana } from './kana';

const RAW = [
 ['abiru', 'あびる浴びる', 'bathe, take a shower', 'i'],
 ['aburagiru', '脂ぎる', 'be greasy', 'g'],
 ['agaru', 'あがる上がる', 'go up, rise', 'g'],
 ['ageru', 'あげるあげる', 'give', 'i'],
 ['akeru', 'あける開ける', 'open', 'i'],
 ['aku', 'あく開く', 'open, become vacant', 'g'],
 ['aogu', 'あおぐ仰ぐ', 'gaze, look up, respect, fan oneself', 'g'],
 ['arawasu', 'あらわす現す', 'show, reveal', 'g'],
 ['aru', 'ある有る', 'have, exist', 'g'],
 ['aseru', 'あせる焦る', 'be in a hurry, panic', 'g'],
 ['atatamaru', 'あたたまる暖まる', 'get warm, warm up', 'g'],
 ['atsumaru', 'あつまる集まる', 'gather, assemble', 'g'],
 ['au', 'あう合う', 'match, fit', 'g'],
 ['awateru', 'あわてる慌てる', 'panic, be flustered', 'i'],
 ['butsukaru', 'ぶつかる', 'hit, collide with, clash', 'g'],
 ['butsukeru', 'ぶつける', 'hit against, throw at', 'i'],
 ['chigau', 'ちがう違う', 'be different, wrong', 'g'],
 ['chiru', 'ちる散る', 'fall, scatter', 'g'],
 ['daku', 'だく抱く', 'embrace, hug', 'g'],
 ['damaru', 'だまる黙る', 'stop talking', 'g'],
 ['damasu', 'だます騙す', 'trick', 'g'],
 ['dasu', 'だす出す', 'extract, take out', 'g'],
 ['dekakeru', 'でかける出かける', 'go out, leave home', 'i'],
 ['dekiru', 'できる出来る', 'be able', 'i'],
 ['dojiru', 'どじる', 'mess up', 'g'],
 ['eru', 'える得る', 'get', 'i'],
 ['fukeru', 'ふける', 'be absorbed in', 'g'],
 ['fuku', 'ふく吹く', 'blow, wipe', 'g'],
 ['fumu', 'ふむ踏む', 'step on', 'g'],
 ['fureru', 'ふれる触れる', 'touch', 'i'],
 ['furu', 'ふる降る', 'fall from the sky', 'g'],
 ['fuseru', 'ふせる伏せる', 'lay face down', 'i'],
 ['futoru', 'ふとる太る', 'get fat, put on weight', 'g'],
 ['fuyasu', 'ふやす増やす', 'increase', 'g'],
 ['ganbaru', 'がんばる頑張る', 'stand firm, try your best', 'g'],
 ['haberu', '侍る', 'attend on', 'g'],
 ['haeru', 'はえる、生える', 'grow', 'i'],
 ['hagemasu', 'はげます励ます', 'encourage', 'g'],
 ['hagemu', 'はげむ励む', 'strive, make every effort', 'g'],
 ['hajimaru', 'はじまる始まる', 'begin', 'g'],
 ['hakobu', 'はこぶ運ぶ', 'carry', 'g'],
 ['haku', 'はく履く', 'put on, wear (feet/legs)', 'g'],
 ['hanareru', 'はなれる離れる', 'separate from, leave', 'i'],
 ['hanasu', 'はなす離す', 'separate, release', 'g'],
 ['hareru', 'はれる晴れる', 'clear up', 'i'],
 ['haru', 'はる張る', 'stick, put something on', 'g'],
 ['hasamu', 'はさむ挟む', 'catch or hold between two things', 'g'],
 ['hayaru', 'はやる流行る', 'become popular', 'g'],
 ['hayasu', 'はやす生やす', 'grow something', 'g'],
 ['hazusu', 'はずす外す', 'remove, unfasten', 'g'],
 ['herasu', 'へらす減らす', 'reduce, decrease', 'g'],
 ['hieru', 'ひえる冷える', 'cool down, become cold', 'i'],
 ['hikaru', 'ひかる光る', 'shine, glitter', 'g'],
 ['hikiukeru', 'ひきうける引き受ける', 'take charge of', 'i'],
 ['hineru', 'ひねる捻る', 'bend, twist', 'g'],
 ['hiromaru', 'ひろまる広まる', 'spread, become popular', 'g'],
 ['hiromeru', 'ひろめる広める', 'spread, make popular', 'i'],
 ['hiyakasu', 'ひやかす冷やかす', 'tease, make fun of', 'g'],
 ['hiyasu', 'ひやす冷やす', 'cool, refrigerate', 'g'],
 ['hodokeru', 'ほどける解ける', 'come untied, loose', 'i'],
 ['hodoku', 'ほどく解く', 'untie', 'g'],
 ['homeru', 'ほめる褒める', 'praise', 'i'],
 ['horeru', 'ほれる惚れる', 'fall in love', 'i'],
 ['horobiru', 'ほろびる滅びる', 'perish', 'g'],
 ['horobosu', 'ほろぼす滅ぼす', 'destroy, ruin', 'g'],
 ['horu', 'ほる掘る', 'dig', 'g'],
 ['hoshigaru', 'ほしがる欲しがる', 'want, desire', 'g'],
 ['hosu', 'ほす干す', 'dry, air', 'g'],
 ['ibaru', 'いばる威張る', 'boast', 'g'],
 ['iiarawasu', 'いいあらわす言い表す', 'describe', 'g'],
 ['iidasu', 'いいだす言い出す', 'suggest, start talking', 'g'],
 ['iifurasu', 'いいふらす言いふらす', 'spread a rumour', 'g'],
 ['iitsukeru', 'いいつける言いつける', 'command', 'i'],
 ['ijimeru', 'いじめる虐める', 'torment, bully', 'i'],
 ['imashimeru', 'いましめる戒める', 'tell off, caution', 'i'],
 ['inoru', 'いのる祈る', 'pray, wish for', 'g'],
 ['ireru', 'いれる入れる', 'put in, let in', 'i'],
 ['iru', 'いる要る', 'need', 'g'],
 ['iru', 'いる居る', 'be', 'i'],
 ['itamu', 'いたむ痛む', 'become hurt, damaged', 'g'],
 ['itsuwaru', 'いつわる偽る', 'deceive, lie', 'g'],
 ['iwau', 'いわう祝う', 'celebrate, congratulate', 'g'],
 ['iyagaru', 'いやがる嫌がる', 'dislike, hate', 'g'],
 ['jukusu', '熟す', 'mature, ripen', 'g'],
 ['kabau', 'かばう庇う', 'protect, look after', 'g'],
 ['kaburu', 'かぶる被る', 'wear (head), put on', 'g'],
 ['kaesu', 'かえす返す', 'give back, return (something)', 'g'],
 ['kagayaku', 'かがやく輝く', 'shine, sparkle', 'g'],
 ['kagiru', 'かぎる限る', 'limit', 'g'],
 ['kajiru', 'かじる齧る', 'gnaw, nibble', 'g'],
 ['kakaeru', 'かかえる抱える', 'hold (in arms), have', 'i'],
 ['kakageru', 'かかげる掲げる', 'raise (a flag), hold up', 'i'],
 ['kakaru', 'かかる掛かる', 'take, begin, be hanging', 'g'],
 ['kakawaru', 'かかわる関わる', 'take part in, affect', 'g'],
 ['kakomu', 'かこむ囲む', 'surround, enclose', 'g'],
 ['kakureru', 'かくれる隠れる', 'hide (oneself)', 'g'],
 ['kakusu', 'かくす隠す', 'hide (something)', 'g'],
 ['kamaeru', 'かまえる構える', 'stand prepared', 'i'],
 ['kamau', 'かまう構う', 'care about, mind', 'g'],
 ['kamu', 'かむ噛む', 'bite', 'g'],
 ['kanashimu', 'かなしむ悲しむ', 'be sad, grieve', 'g'],
 ['kanau', 'かなう適う', 'suit, conform to', 'g'],
 ['karakau', 'からかう', 'make fun of, play jokes on', 'g'],
 ['karasu', 'からす枯らす', 'let wither', 'g'],
 ['kareru', 'かれる枯れる', 'wither', 'i'],
 ['kasanaru', 'かさなる重なる', 'be piled up, overlap', 'g'],
 ['kasaneru', 'かさねる重ねる', 'pile up, repeat', 'i'],
 ['kasegu', 'かせぐ稼ぐ', 'make money, earn a living', 'g'],
 ['kasumu', 'かすむ霞む', 'become blurred, hazy', 'g'],
 ['katamaru', 'かたまる固まる', 'become hard, bunch up', 'g'],
 ['katameru', 'かためる固める', 'strengthen, harden', 'i'],
 ['katamuku', 'かたむく傾く', 'lean, tilt', 'g'],
 ['katazukeru', 'かたづける片付ける', 'finish, tidy up', 'i'],
 ['katsugu', 'かつぐ担ぐ', 'carry on shoulders', 'g'],
 ['kawaigaru', 'かわいがる可愛がる', 'love, be affectionate', 'g'],
 ['kawakasu', 'かわかす乾かす', 'dry', 'g'],
 ['kawaku', 'かわく乾く', 'become dry', 'g'],
 ['kayou', 'かよう通う', 'commute', 'g'],
 ['kazaru', 'かざる飾る', 'decorate, display', 'g'],
 ['kazoeru', 'かぞえる数える', 'count', 'i'],
 ['keru', 'ける蹴る', 'kick', 'g'],
 ['kesu', 'けす消す', 'turn off, erase', 'g'],
 ['kieru', 'きえる消える', 'vanish, go out', 'i'],
 ['kikaeru', 'きかえる着換える', 'get changed', 'i'],
 ['kikoeru', 'きこえる聞こえる', 'be audible, able to hear', 'i'],
 ['kimaru', 'きまる決まる', 'be decided, agreed upon', 'g'],
 ['kinjiru', 'きんじる禁じる', 'ban, prohibit', 'i'],
 ['kireru', 'きれる切れる', 'break, cut off, expire', 'i'],
 ['kizukau', 'きづかう気遣う', 'worry about, consider', 'g'],
 ['kizuku', 'きづく気付く', 'sense, realize, notice', 'g'],
 ['kizutsukeru', 'きずつける傷つける', 'wound, damage, harm', 'i'],
 ['koboreru', 'こぼれる', 'spill, overflow', 'i'],
 ['kobosu', 'こぼす', 'spill', 'g'],
 ['koeru', 'こえる', 'get fat / cross over, exceed', 'i'],
 ['kogeru', 'こげる焦げる', 'be burned, charred', 'i'],
 ['kokorozasu', 'こころざす志す', 'aspire to', 'g'],
 ['komu', 'こむ込む', 'become crowded', 'g'],
 ['konomu', 'このむ好む', 'like', 'g'],
 ['korasu', 'こらす凝らす', 'concentrate', 'g'],
 ['korobu', 'ころぶ転ぶ', 'fall down', 'g'],
 ['korosu', 'ころす殺す', 'kill', 'g'],
 ['koshikakeru', 'こしかける腰掛ける', 'sit (western style)', 'i'],
 ['koshiraeru', 'こしらえる拵える', 'make, manufacture', 'i'],
 ['kosu', 'こす越す', 'cross, pass, move ahead', 'g'],
 ['kotonaru', 'ことなる異なる', 'be different from', 'g'],
 ['kowagaru', 'こわがる怖がる', 'fear', 'g'],
 ['kowareru', 'こわれる壊れる', 'get broken', 'i'],
 ['kowasu', 'こわす壊す', 'break, smash', 'g'],
 ['kudaku', 'くだく砕く', 'crush, smash', 'g'],
 ['kudoku', 'くどく口説く', 'persuade', 'g'],
 ['kuichigau', 'くいちがう食い違う', 'clash, disagree', 'g'],
 ['kumoru', 'くもる曇る', 'get cloudy', 'g'],
 ['kumu', 'くむ組む', 'unite, put together', 'g'],
 ['kuraberu', 'くらべる比べる', 'compare', 'i'],
 ['kuramu', 'くらむ眩む', 'be blinded, get dizzy', 'g'],
 ['kurasu', 'くらす暮らす', 'live', 'g'],
 ['kurikaesu', 'くりかえす繰り返す', 'repeat', 'g'],
 ['kurushimeru', 'くるしませる苦しませる', 'inflict pain, torment', 'i'],
 ['kurushimu', 'くるしむ苦しむ', 'suffer', 'g'],
 ['kuruu', 'くるう狂う', 'go mad, be out of order', 'g'],
 ['kusaru', 'くさる腐る', 'decay, go bad', 'g'],
 ['kuwadateru', '企てる', 'plan, scheme', 'i'],
 ['kuwaeru', 'くわえる加える', 'add to, include', 'i'],
 ['kuwawaru', 'くわわる加わる', 'join, participate', 'g'],
 ['kuzureru', 'くずれる崩れる', 'collapse, cave in', 'i'],
 ['kuzusu', 'くずす崩す', 'destroy, break down', 'g'],
 ['machigaeru', 'まちがえる間違える', 'make a mistake', 'i'],
 ['machigau', 'まちがう間違う', 'be mistaken, make a mistake', 'g'],
 ['magaru', 'まがる曲がる', 'turn, bend', 'g'],
 ['mageru', 'まげる曲げる', 'bend, twist', 'i'],
 ['mairu', 'まいる参る', 'come/go (humble)', 'g'],
 ['majiru', 'まじる混じる', 'be mixed, get mingled with', 'g'],
 ['makasu', 'まかす負かす', 'defeat', 'g'],
 ['mamoru', 'まもる守る', 'protect', 'g'],
 ['manabu', 'まなぶ学ぶ', 'learn, study', 'g'],
 ['maneku', 'まねく招く', 'invite, beckon to', 'g'],
 ['matsuru', 'まつる祀る', 'worship', 'g'],
 ['mawaru', 'まわる回る', 'go round', 'g'],
 ['mayou', 'まよう迷う', 'be puzzled', 'g'],
 ['mazeru', 'まぜる混ぜる', 'mix', 'i'],
 ['medatsu', 'めだつ目立つ', 'attract attention, stand out', 'g'],
 ['mieru', 'みえる見える', 'be visible, able to see', 'i'],
 ['migaku', 'みがく磨く', 'polish', 'g'],
 ['miharu', 'みはる見張る', 'stand guard, keep lookout', 'g'],
 ['minogasu', 'みのがす見逃す', 'overlook, let pass', 'g'],
 ['minoru', 'みのる実る', 'ripen, bear fruit', 'g'],
 ['mitasu', 'みたす満たす', 'satisfy', 'g'],
 ['mitomeru', 'みとめる認める', 'admit, recognize', 'i'],
 ['modoru', 'もどる戻る', 'return, go back', 'g'],
 ['modosu', 'もどす戻す', 'return, put back', 'g'],
 ['mokaru', 'もうかる儲かる', 'be profitable, make money', 'g'],
 ['mokeru', 'もうける儲ける', 'profit, make money', 'i'],
 ['morasu', 'もらす漏らす', 'leak, disclose', 'g'],
 ['morau', 'もらう貰う', 'receive, get', 'g'],
 ['moreru', 'もれる漏れる', 'leak, escape', 'i'],
 ['moteru', 'もてる', 'be popular', 'i'],
 ['motozuku', 'もとづく基づく', 'be based on', 'g'],
 ['motsu', 'もつ持つ', 'have, hold, own', 'g'],
 ['mukaeru', 'むかえる迎える', 'greet, meet, welcome', 'i'],
 ['mukau', 'むかう向かう', 'face, turn toward', 'g'],
 ['musubu', 'むすぶ結ぶ', 'tie, knot, make a contract', 'g'],
 ['nagameru', 'ながめる眺める', 'watch, view', 'i'],
 ['nagareru', 'ながれる流れる', 'flow, be called off', 'i'],
 ['nagasu', 'ながす流す', 'pour, let flow', 'g'],
 ['naguru', 'なぐる殴る', 'punch, hit', 'g'],
 ['nagusameru', 'なぐさめる慰める', 'comfort, console', 'i'],
 ['najimu', 'なじむ馴染む', 'get used to, adapt to', 'g'],
 ['nakunaru', 'なくなる無くなる', 'be missing, vanish', 'g'],
 ['nakusu', 'なくす無くす', 'lose, remove', 'g'],
 ['namakeru', 'なまける怠ける', 'be lazy', 'i'],
 ['nameru', 'なめる舐める', 'lick', 'i'],
 ['naoru', 'なおる直る', 'be cured, healed', 'g'],
 ['narau', 'ならう習う', 'learn', 'g'],
 ['nareru', 'なれる慣れる', 'get used to, become familiar', 'i'],
 ['naru', 'なる', 'become', 'g'],
 ['nejiru', '捩じる', 'twist', 'g'],
 ['nemuru', 'ねむる眠る', 'fall asleep', 'g'],
 ['neru', 'ねる練る', 'temper, refine, knead', 'g'],
 ['nigasu', 'にがす逃がす', 'let escape', 'g'],
 ['nigeru', 'にげる逃げる', 'run away, escape', 'i'],
 ['nigiru', 'にぎる握る', 'grasp', 'g'],
 ['niramu', 'にらむ睨む', 'glare at, keep an eye on', 'g'],
 ['niru', 'にる似る', 'resemble, be similar to', 'i'],
 ['nobasu', 'のばす', 'postpone, extend', 'g'],
 ['noboru', 'のぼる登る', 'climb', 'g'],
 ['nokoru', 'のこる残る', 'left over, remain', 'g'],
 ['nokosu', 'のこす残す', 'leave behind, save', 'g'],
 ['norikaeru', 'のりかえる乗り換える', 'transit', 'i'],
 ['nukeru', 'ぬける抜ける', 'be extracted, come out', 'i'],
 ['nuku', 'ぬく抜く', 'extract', 'g'],
 ['nureru', 'ぬれる濡れる', 'become wet', 'i'],
 ['nuru', 'ぬる塗る', 'paint, smear on', 'g'],
 ['nusumu', 'ぬすむ盗む', 'steal', 'g'],
 ['ochiru', 'おちる落ちる', 'fall, fail, go down', 'i'],
 ['okoru', 'おこる怒る', 'get angry', 'g'],
 ['okosu', 'おこす起こす', 'wake somebody up', 'g'],
 ['oku', 'おく置く', 'put, place', 'g'],
 ['okureru', 'おくれる遅れる', 'be late, lag behind', 'i'],
 ['omou', 'おもう思う', 'think', 'g'],
 ['oreru', 'おれる折れる', 'be broken, snap', 'i'],
 ['orosu', 'おろす降ろす', 'drop off, unload', 'g'],
 ['osaeru', 'おさえる抑える', 'restrain, control', 'i'],
 ['oshimu', 'おしむ惜しむ', 'regret, be reluctant', 'g'],
 ['osoreru', 'おそれる恐れる', 'fear, be in awe of', 'i'],
 ['osou', 'おそう襲う', 'attack', 'g'],
 ['otoru', 'おとる劣る', 'be worse than, inferior to', 'g'],
 ['ou', 'おう追う', 'chase, drive away', 'g'],
 ['oyobu', 'およぶ及ぶ', 'reach, extend to', 'g'],
 ['sadameru', 'さだめる定める', 'decide, establish', 'i'],
 ['sagaru', 'さがる下がる', 'fall, drop, hang', 'g'],
 ['sageru', 'さげる下げる', 'lower, hang', 'i'],
 ['saku', 'さく咲く', 'bloom', 'g'],
 ['samatageru', 'さまたげる妨げる', 'hinder, obstruct', 'i'],
 ['sasaeru', 'ささえる支える', 'support', 'i'],
 ['sasou', 'さそう誘う', 'invite, tempt', 'g'],
 ['sasu', 'さす刺す', 'point out, sting, stab', 'g'],
 ['sawagu', 'さわぐ騒ぐ', 'make a noise, be rowdy', 'g'],
 ['sawaru', 'さわる触る', 'touch or feel with hands', 'g'],
 ['shaberu', 'しゃべる喋る', 'chatter', 'g'],
 ['shibaru', 'しばる縛る', 'tie up, bind', 'g'],
 ['shikaru', 'しかる叱る', 'scold, tell off', 'g'],
 ['shiku', 'しく敷く', 'spread out, lay', 'g'],
 ['shimaru', 'しまる閉まる', 'close, be closed', 'g'],
 ['shimau', 'しまう', 'put away', 'g'],
 ['shimesu', 'しめす示す', 'indicate, point out', 'g'],
 ['shiraberu', 'しらべる調べる', 'check, investigate', 'i'],
 ['shiraseru', 'しらせる知らせる', 'notify', 'i'],
 ['shizumaru', 'しずまる静まる', 'grow quiet', 'g'],
 ['shizumu', 'しずむ沈む', 'feel depressed, sink', 'g'],
 ['sodateru', 'そだてる育てる', 'to rear, to bring up', 'i'],
 ['sodatsu', 'そだつ育つ', 'grow up, be raised', 'g'],
 ['suberu', 'すべる滑る', 'slip', 'g'],
 ['sugiru', 'すぎる過ぎる', 'pass, exceed', 'i'],
 ['sugosu', 'すごす過ごす', 'spend (time)', 'g'],
 ['sugureru', 'すぐれる優れる', 'excel, be superior', 'i'],
 ['suku', 'すく空く', 'become empty, uncrowded', 'g'],
 ['sukuu', 'すくう救う', 'rescue, save', 'g'],
 ['sumu', 'すむ住む', 'live, reside', 'g'],
 ['susumu', 'すすむ進む', 'go forward, advance', 'g'],
 ['suteru', 'すてる捨てる', 'throw away', 'i'],
 ['suu', 'すう吸う', 'inhale, sip, smoke', 'g'],
 ['suwaru', 'すわる座る', 'sit', 'g'],
 ['takuramu', 'たくらむ企む', 'plot, scheme', 'g'],
 ['takuwaeru', 'たくわえる蓄える', 'save money, store', 'i'],
 ['tameru', 'ためる', 'save, store, accumulate', 'i'],
 ['tamesu', 'ためす試す', 'test, try, taste', 'g'],
 ['tanoshimu', 'たのしむ楽しむ', 'enjoy, have fun', 'g'],
 ['taoreru', 'たおれる倒れる', 'fall down, collapse', 'i'],
 ['taosu', 'たおす倒す', 'overthrow, knock down', 'g'],
 ['tariru', 'たりる足りる', 'be enough, sufficient', 'i'],
 ['tasu', 'たす足す', 'add', 'g'],
 ['tasukaru', 'たすかる助かる', 'be saved', 'g'],
 ['tasukeru', 'たすける助ける', 'help', 'i'],
 ['tatakau', '戦う', 'fight against, struggle against', 'g'],
 ['tatamu', 'たたむ畳む', 'fold', 'g'],
 ['tsugu', 'つぐ次ぐ', 'be next', 'g'],
 ['tsukareru', 'つかれる疲れる', 'get tired', 'i'],
 ['tsukeru', 'つける点ける', 'turn on, light', 'i'],
 ['tsureru', 'つれる連れる', 'lead', 'i'],
 ['tsuru', 'つる釣る', 'fish', 'g'],
 ['tsutomeru', 'つとめる勤める', 'work for', 'i'],
 ['tsutsumu', 'つつむ包む', 'wrap', 'g'],
 ['tsuyomaru', 'つよまる強まる', 'become stronger', 'g'],
 ['tsuyomeru', 'つよめる強める', 'strengthen', 'i'],
 ['tsuzuku', 'つづく続く', 'continue, follow', 'g'],
 ['ugeru', '植える', 'plant', 'i'],
 ['ugokasu', '動かす', 'move, operate', 'g'],
 ['ukabu', '浮かぶ', 'float, come to mind', 'g'],
 ['umu', '生む', 'produce, give birth', 'g'],
 ['ureru', 'うれる売れる', 'be sold', 'i'],
 ['uru', 'うる売る', 'sell', 'g'],
 ['ushinau', '失う', 'lose, part with', 'g'],
 ['utagau', '疑う', 'doubt, suspect', 'g'],
 ['utsu', '打つ', 'hit, shoot', 'g'],
 ['utsusu', '映す', 'photograph, copy, reflect', 'g'],
 ['wakareru', 'わかれる別れる', 'part, separate, be divorced', 'i'],
 ['wakasu', 'わかす沸かす', 'bring to the boil', 'g'],
 ['waku', 'わく沸く', 'boil', 'g'],
 ['wataru', 'わたる渡る', 'cross', 'g'],
 ['yakeru', 'やける焼ける', 'burn', 'i'],
 ['yareru', 'やれる', 'can do', 'i'],
 ['yaseru', 'やせる', 'lose weight, get thin', 'i'],
 ['yogoreru', 'よごれる汚れる', 'become dirty', 'i'],
 ['yogosu', 'よごす汚す', 'make dirty, stain', 'g'],
 ['yorokobasu', 'よろこばす喜ばす', 'delight, give pleasure', 'g'],
];

function splitJapanese(raw, romaji) {
  // raw = optional hiragana prefix + kanji + okurigana, or just kanji/just kana/empty
  let hiragana = '';
  let dictionary = '';
  if (raw) {
    let rest = raw.replace(/[、, \s]/g, '');
    const leadMatch = rest.match(/^[ぁ-ゖ゛゜ーー]+/);
    if (leadMatch) {
      hiragana = leadMatch[0];
      rest = rest.slice(leadMatch[0].length);
    }
    dictionary = rest;
  }
  if (!hiragana) hiragana = romaji2kana(romaji);
  if (!dictionary) dictionary = hiragana;
  return { hiragana, dictionary };
}

export const newVerbs = RAW.map(([romaji, jp, meaning_en, g]) => ({
  romaji,
  meaning_en,
  group: g === 'i' ? 'ichidan' : g === 'irr' ? 'irregular' : 'godan',
  level: 'N3',
  ...splitJapanese(jp, romaji),
}));